#!/bin/bash
set -e
sudo sed -i "/#\$nrconf{restart} = 'i';/s/.*/\$nrconf{restart} = 'a';/" /etc/needrestart/needrestart.conf
sudo apt-get -qq update
sudo apt-get remove libqt4-dev || true
sudo apt-get -q --assume-yes install dpkg-dev
cd /mount/bareos/
dpkg-checkbuilddeps 2> /tmp/dpkg-builddeps || true
cat /tmp/dpkg-builddeps
sed -e "s/^.*:.*:\s//" -e "s/\s([^)]*)//g" -e "s/|/ /g" -e "s/ /\n/g" /tmp/dpkg-builddeps > /tmp/build_depends
sudo apt-get -q --assume-yes install fakeroot
cat /tmp/build_depends | while read pkg; do
  echo "installing $pkg"
  sudo apt-get -q --assume-yes install $pkg || true
done
sudo apt-get -q --assume-yes install python2-dev python3-dev python3-pip python3-sphinx graphviz plantuml googletest libgtest-dev libgmock-dev
sudo pip3 install sphinx-issues sphinxcontrib.actdiag sphinxcontrib.blockdiag sphinxcontrib.nwdiag sphinxcontrib.plantuml sphinxcontrib.seqdiag sphinx-csv-filter m2r2 sphinx_copybutton sphinx_rtd_theme
