#!/bin/bash
set -e
sudo apt install software-properties-common
wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main"
sudo apt-get update
sudo apt-get install postgresql-14
sudo systemctl restart postgresql
sudo -u postgres createuser --createdb --createrole $USER
